---
:at_tags: false
:autolink: true
:color: true
:inline_footnotes: false
:intra_emphasis: true
:lax_spacing: true
:links: :inline
:local_images: false
:pager: true
:preserve_linebreaks: false
:remote_images: false
:syntax_higlight: false
:taskpaper: false
:theme: default
:width: 140
:wiki_links: false
