os:
  editPreset: nvim
gui:
  showIcons: true
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red
git:
  paging:
    pager: delta --paging=never
customCommands:
  - key: E
    prompts:
      - type: input
        title: Enter commit message
        initialValue: ""
    description: Add empty commit
    context: commits
    command: git commit --allow-empty -m "{{index .PromptResponses 0}}"
    loadingText: Committing empty commit...
  - key: V
    description: Extract the latest Gitlab issue from commits
    context: global
    command: git log --oneline -10|rg '[-\w]+/\w+#\d+' -o|head -1|tr -d '\n'|pbcopy
    loadingText: Copied the latest Gitlab issue
